# Generated by Django 4.2.27 on 2026-01-18 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistInfo',
            fields=[
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='artist_info', serialize=False, to='channel.channel')),
                ('bio', models.TextField(blank=True, default='')),
                ('bio_summary', models.TextField(blank=True, default='')),
                ('lastfm_url', models.URLField(blank=True, default='', max_length=500)),
                ('lastfm_mbid', models.CharField(blank=True, default='', max_length=100)),
                ('lastfm_listeners', models.IntegerField(default=0)),
                ('lastfm_playcount', models.IntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('fanart_id', models.CharField(blank=True, default='', max_length=100)),
                ('similar_artists', models.JSONField(blank=True, default=list)),
                ('metadata_fetched', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Artist Info',
            },
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(db_index=True, max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('channel_id', models.CharField(db_index=True, max_length=50)),
                ('channel_name', models.CharField(max_length=200)),
                ('duration', models.IntegerField(help_text='Duration in seconds')),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('published_date', models.DateTimeField()),
                ('downloaded_date', models.DateTimeField(auto_now_add=True)),
                ('view_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('audio_format', models.CharField(default='m4a', max_length=20)),
                ('bitrate', models.IntegerField(blank=True, help_text='Bitrate in kbps', null=True)),
                ('play_count', models.IntegerField(default=0)),
                ('last_played', models.DateTimeField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(help_text='User who owns this audio file', on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='LocalAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('artist', models.CharField(blank=True, max_length=200)),
                ('album', models.CharField(blank=True, max_length=200)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('track_number', models.IntegerField(blank=True, null=True)),
                ('file', models.FileField(max_length=500, upload_to='local_audio/%Y/%m/')),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('audio_format', models.CharField(blank=True, max_length=20)),
                ('bitrate', models.IntegerField(blank=True, help_text='Bitrate in kbps', null=True)),
                ('sample_rate', models.IntegerField(blank=True, help_text='Sample rate in Hz', null=True)),
                ('channels', models.IntegerField(blank=True, help_text='Number of audio channels', null=True)),
                ('cover_art', models.ImageField(blank=True, null=True, upload_to='local_audio_covers/%Y/%m/')),
                ('original_filename', models.CharField(max_length=500)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('play_count', models.IntegerField(default=0)),
                ('last_played', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='User-defined tags')),
                ('notes', models.TextField(blank=True, help_text='User notes about this file')),
                ('is_favorite', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(help_text='User who uploaded this file', on_delete=django.db.models.deletion.CASCADE, related_name='local_audio_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_date'],
            },
        ),
        migrations.CreateModel(
            name='LocalAudioPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='local_playlist_covers/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Lyrics',
            fields=[
                ('audio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='lyrics', serialize=False, to='audio.audio')),
                ('synced_lyrics', models.TextField(blank=True, default='')),
                ('plain_lyrics', models.TextField(blank=True, default='')),
                ('is_instrumental', models.BooleanField(default=False)),
                ('source', models.CharField(default='lrclib', max_length=50)),
                ('language', models.CharField(blank=True, default='', max_length=10)),
                ('fetched_date', models.DateTimeField(auto_now=True)),
                ('fetch_attempted', models.BooleanField(default=False)),
                ('fetch_attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'Lyrics',
                'ordering': ['-fetched_date'],
            },
        ),
        migrations.CreateModel(
            name='MusicMetadata',
            fields=[
                ('audio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='music_metadata', serialize=False, to='audio.audio')),
                ('album_name', models.CharField(blank=True, default='', max_length=500)),
                ('album_artist', models.CharField(blank=True, default='', max_length=500)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('track_number', models.IntegerField(blank=True, null=True)),
                ('disc_number', models.IntegerField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, default='', max_length=200)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('lastfm_url', models.URLField(blank=True, default='', max_length=500)),
                ('lastfm_mbid', models.CharField(blank=True, default='', help_text='MusicBrainz ID', max_length=100)),
                ('play_count', models.IntegerField(default=0, help_text='Global play count from Last.fm')),
                ('listeners', models.IntegerField(default=0, help_text='Unique listeners from Last.fm')),
                ('fanart_artist_id', models.CharField(blank=True, default='', max_length=100)),
                ('fanart_album_id', models.CharField(blank=True, default='', max_length=100)),
                ('metadata_fetched', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Music Metadata',
            },
        ),
        migrations.CreateModel(
            name='LyricsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('artist_name', models.CharField(max_length=500)),
                ('album_name', models.CharField(blank=True, default='', max_length=500)),
                ('duration', models.IntegerField()),
                ('synced_lyrics', models.TextField(blank=True, default='')),
                ('plain_lyrics', models.TextField(blank=True, default='')),
                ('is_instrumental', models.BooleanField(default=False)),
                ('language', models.CharField(blank=True, default='', max_length=10)),
                ('source', models.CharField(default='lrclib', max_length=50)),
                ('cached_date', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('access_count', models.IntegerField(default=0)),
                ('not_found', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['title', 'artist_name', 'duration'], name='audio_lyric_title_684191_idx'), models.Index(fields=['cached_date'], name='audio_lyric_cached__1afcf9_idx')],
                'unique_together': {('title', 'artist_name', 'album_name', 'duration')},
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=100)),
                ('channel_name', models.CharField(max_length=255)),
                ('channel_description', models.TextField(blank=True)),
                ('channel_thumbnail', models.URLField(blank=True)),
                ('subscribed', models.BooleanField(default=False)),
                ('subscriber_count', models.IntegerField(default=0)),
                ('video_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_channels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AudioProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, help_text='Current position in seconds')),
                ('completed', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='audio.audio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork_type', models.CharField(choices=[('audio_thumbnail', 'Audio Thumbnail'), ('audio_cover', 'Audio Cover Art'), ('album_cover', 'Album Cover'), ('artist_image', 'Artist Image'), ('artist_banner', 'Artist Banner'), ('artist_logo', 'Artist Logo')], max_length=50)),
                ('source', models.CharField(choices=[('youtube', 'YouTube'), ('lastfm', 'Last.fm'), ('fanart', 'Fanart.tv'), ('manual', 'Manual Upload')], max_length=50)),
                ('url', models.URLField(max_length=1000)),
                ('local_path', models.CharField(blank=True, default='', max_length=500)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('file_size', models.IntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('priority', models.IntegerField(default=0)),
                ('fetched_date', models.DateTimeField(auto_now_add=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('audio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='audio.audio')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='channel.channel')),
            ],
            options={
                'ordering': ['-priority', '-fetched_date'],
            },
        ),
        migrations.CreateModel(
            name='LocalAudioPlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_items', to='audio.localaudio')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='audio.localaudioplaylist')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('playlist', 'audio')},
            },
        ),
        migrations.AddIndex(
            model_name='localaudioplaylist',
            index=models.Index(fields=['owner', '-created_date'], name='audio_local_owner_i_c4f784_idx'),
        ),
        migrations.AddIndex(
            model_name='localaudio',
            index=models.Index(fields=['owner', '-uploaded_date'], name='audio_local_owner_i_39741a_idx'),
        ),
        migrations.AddIndex(
            model_name='localaudio',
            index=models.Index(fields=['owner', 'is_favorite'], name='audio_local_owner_i_a736b3_idx'),
        ),
        migrations.AddIndex(
            model_name='localaudio',
            index=models.Index(fields=['owner', 'artist'], name='audio_local_owner_i_da5456_idx'),
        ),
        migrations.AddIndex(
            model_name='localaudio',
            index=models.Index(fields=['owner', 'album'], name='audio_local_owner_i_a7607b_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['user', 'channel_id'], name='audio_chann_user_id_73587a_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['user', 'subscribed'], name='audio_chann_user_id_98fe06_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('user', 'channel_id')},
        ),
        migrations.AddIndex(
            model_name='audioprogress',
            index=models.Index(fields=['user', 'audio'], name='audio_audio_user_id_9b9360_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='audioprogress',
            unique_together={('user', 'audio')},
        ),
        migrations.AddIndex(
            model_name='audio',
            index=models.Index(fields=['owner', 'youtube_id'], name='audio_audio_owner_i_78bfce_idx'),
        ),
        migrations.AddIndex(
            model_name='audio',
            index=models.Index(fields=['owner', 'channel_id'], name='audio_audio_owner_i_0f4a03_idx'),
        ),
        migrations.AddIndex(
            model_name='audio',
            index=models.Index(fields=['owner', '-published_date'], name='audio_audio_owner_i_51301d_idx'),
        ),
        migrations.AddIndex(
            model_name='audio',
            index=models.Index(fields=['owner', 'is_favorite'], name='audio_audio_owner_i_48f87c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='audio',
            unique_together={('owner', 'youtube_id')},
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['audio', 'artwork_type'], name='audio_artwo_audio_i_eee8cd_idx'),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['channel', 'artwork_type'], name='audio_artwo_channel_6991b9_idx'),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['is_primary'], name='audio_artwo_is_prim_9e7bd0_idx'),
        ),
    ]
