# Generated by Django 4.2.27 on 2026-02-02 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0005_smart_radio'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='radiotrackfeedback',
            new_name='audio_radio_user_id_ddcf35_idx',
            old_name='audio_radio_user_id_youtube_idx',
        ),
        migrations.RenameIndex(
            model_name='radiotrackfeedback',
            new_name='audio_radio_user_id_11d225_idx',
            old_name='audio_radio_user_id_channel_idx',
        ),
        migrations.RenameIndex(
            model_name='radiotrackfeedback',
            new_name='audio_radio_user_id_09419c_idx',
            old_name='audio_radio_user_id_created_idx',
        ),
        migrations.AlterField(
            model_name='radiosession',
            name='variety_level',
            field=models.IntegerField(default=50, help_text='0-100, higher = more variety, lower = stick to similar'),
        ),
    ]
