# Generated by Django 4.2.30 on 2026-08-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0008_biginteger_view_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='chapters',
            field=models.JSONField(blank=True, default=list, help_text='Chapter markers [{title,start,end}]'),
        ),
    ]
