# Generated by Django 4.2.30 on 2026-08-11 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0009_audio_chapters'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('start_seconds', models.FloatField(help_text='Segment start offset in seconds')),
                ('end_seconds', models.FloatField(help_text='Segment end offset in seconds')),
                ('order', models.IntegerField(default=0, help_text='Position within the split')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('audio', models.ForeignKey(help_text='The mix this segment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='audio.audio')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['audio', 'order'], name='audio_audio_audio_i_41d99a_idx')],
            },
        ),
    ]
