# Generated by Django 4.2.30 on 2026-08-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0010_audiosegment'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='loudness_lufs',
            field=models.FloatField(blank=True, help_text='Integrated loudness (LUFS)', null=True),
        ),
    ]
