# Generated by Django 4.2.30 on 2026-08-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0011_audio_loudness_lufs'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='bpm',
            field=models.FloatField(blank=True, help_text='Estimated tempo (beats/min)', null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='energy',
            field=models.FloatField(blank=True, help_text='Normalized RMS energy 0..1', null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='feature_vector',
            field=models.JSONField(blank=True, default=list, help_text='Normalized 6-dim sonic feature vector'),
        ),
        migrations.AddField(
            model_name='audio',
            name='music_key',
            field=models.CharField(blank=True, help_text="Estimated musical key, e.g. 'A'", max_length=8),
        ),
        migrations.AddField(
            model_name='radiosession',
            name='energy_curve',
            field=models.CharField(blank=True, help_text='Auto-DJ energy curve: focus|party|winddown', max_length=12),
        ),
        migrations.AlterField(
            model_name='radiosession',
            name='mode',
            field=models.CharField(choices=[('track', 'Based on Track'), ('artist', 'Based on Artist'), ('favorites', 'Favorites Mix'), ('discovery', 'Discovery Mode'), ('recent', 'Recently Added'), ('sonic', 'Sonic Similarity'), ('autodj', 'Auto-DJ')], default='track', max_length=20),
        ),
    ]
