# Generated by Django - Initial migration for user app

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('two_factor_secret', models.CharField(blank=True, max_length=32, null=True)),
                ('backup_codes', models.JSONField(blank=True, default=list)),
                ('storage_quota_gb', models.IntegerField(default=50, help_text='Storage quota in GB')),
                ('storage_used_gb', models.FloatField(default=0.0, help_text='Storage used in GB')),
                ('max_channels', models.IntegerField(default=50, help_text='Maximum channels allowed')),
                ('max_playlists', models.IntegerField(default=100, help_text='Maximum playlists allowed')),
                ('user_notes', models.TextField(blank=True, help_text='Admin notes about this user')),
                ('avatar', models.CharField(blank=True, help_text='Path to user avatar image or preset avatar number (1-5)', max_length=500, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserYouTubeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(help_text='Friendly name for this YouTube account', max_length=200)),
                ('youtube_channel_id', models.CharField(blank=True, max_length=50)),
                ('youtube_channel_name', models.CharField(blank=True, max_length=200)),
                ('cookies_file', models.TextField(blank=True, help_text='YouTube cookies for authenticated downloads')),
                ('is_active', models.BooleanField(default=True)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('auto_download', models.BooleanField(default=True, help_text='Automatically download new videos')),
                ('download_quality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('ultra', 'Ultra')], default='medium', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
                'unique_together': {('user', 'account_name')},
            },
        ),
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='dark', help_text='UI theme preference', max_length=50)),
                ('volume', models.IntegerField(default=80, help_text='Player volume (0-100)')),
                ('repeat_mode', models.CharField(choices=[('none', 'None'), ('one', 'Repeat One'), ('all', 'Repeat All')], default='none', help_text='Player repeat mode', max_length=20)),
                ('shuffle_enabled', models.BooleanField(default=False, help_text='Shuffle mode enabled')),
                ('audio_quality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('best', 'Best')], default='high', help_text='Preferred audio quality', max_length=20)),
                ('items_per_page', models.IntegerField(default=50, help_text='Items per page in lists')),
                ('extra_settings', models.JSONField(blank=True, default=dict, help_text='Additional user settings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Configuration',
                'verbose_name_plural': 'User Configurations',
            },
        ),
    ]
