# Generated by Django migration for smart shuffle and crossfade settings

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfig',
            name='smart_shuffle_enabled',
            field=models.BooleanField(default=True, help_text='Smart shuffle mode - avoids recently played songs'),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='smart_shuffle_history_size',
            field=models.IntegerField(default=10, help_text='Number of recent songs to avoid in smart shuffle (5-50)'),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='crossfade_enabled',
            field=models.BooleanField(default=False, help_text='Enable crossfade between tracks'),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='crossfade_duration',
            field=models.IntegerField(default=3, help_text='Crossfade duration in seconds (1-12)'),
        ),
    ]
