# Generated by Django 4.2.27 on 2026-01-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_add_visualizer_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfig',
            name='prefetch_enabled',
            field=models.BooleanField(default=True, help_text='Enable automatic prefetching of upcoming tracks'),
        ),
    ]
