# Generated by Django 4.2.27 on 2026-01-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_crossfade_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfig',
            name='visualizer_theme',
            field=models.CharField(default='rounded-bars', help_text='Audio visualizer theme', max_length=50),
        ),
    ]
