# Generated by Django 4.2.27 on 2026-02-01 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_userconfig_visualizer_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfig',
            name='seek_duration',
            field=models.IntegerField(default=3, help_text='Seek duration in seconds (3, 5, or 10)'),
        ),
    ]
