# Generated by Django 4.2.28 on 2026-02-23 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_add_seek_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for this API key', max_length=100)),
                ('key_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('key_prefix', models.CharField(help_text='First 8 chars of the key for identification', max_length=8)),
                ('permission', models.CharField(choices=[('read', 'Read Only'), ('write', 'Read & Write'), ('admin', 'Full Admin')], default='read', max_length=20)),
                ('scope_stats', models.BooleanField(default=True, help_text='Can access stats/widget API')),
                ('scope_audio', models.BooleanField(default=False, help_text='Can access audio API')),
                ('scope_channels', models.BooleanField(default=False, help_text='Can access channels API')),
                ('scope_playlists', models.BooleanField(default=False, help_text='Can access playlists API')),
                ('scope_downloads', models.BooleanField(default=False, help_text='Can access downloads API')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiry date', null=True)),
                ('user', models.ForeignKey(help_text='User who owns this API key', on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
            },
        ),
    ]
