# Generated by Django 4.2.27 on 2026-01-18 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('playlist_type', models.CharField(choices=[('youtube', 'YouTube Playlist'), ('custom', 'Custom Playlist')], default='youtube', max_length=20)),
                ('channel_id', models.CharField(blank=True, max_length=50)),
                ('channel_name', models.CharField(blank=True, max_length=200)),
                ('subscribed', models.BooleanField(default=False)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, help_text='Playlist is active and available')),
                ('last_refresh', models.DateTimeField(blank=True, help_text='Last time playlist metadata was refreshed', null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('success', 'Success'), ('failed', 'Failed'), ('stale', 'Stale')], default='pending', help_text='Current sync status', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Last error message if sync failed')),
                ('item_count', models.IntegerField(default=0, help_text='Total items in playlist')),
                ('downloaded_count', models.IntegerField(default=0, help_text='Downloaded items count')),
                ('auto_download', models.BooleanField(default=False, help_text='Auto-download new items in this playlist')),
                ('owner', models.ForeignKey(help_text='User who owns this playlist', on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused')], default='pending', max_length=20)),
                ('total_items', models.IntegerField(default=0)),
                ('downloaded_items', models.IntegerField(default=0)),
                ('failed_items', models.IntegerField(default=0)),
                ('total_size_bytes', models.BigIntegerField(default=0, help_text='Total size in bytes')),
                ('downloaded_size_bytes', models.BigIntegerField(default=0, help_text='Downloaded size in bytes')),
                ('quality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('ultra', 'Ultra')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('download_path', models.CharField(blank=True, help_text='Path to downloaded files', max_length=500)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='playlist.playlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_downloads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_items', to='audio.audio')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='playlist.playlist')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('playlist', 'audio')},
            },
        ),
        migrations.CreateModel(
            name='PlaylistDownloadItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('position', models.IntegerField(default=0)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('downloaded_bytes', models.BigIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_download_items', to='audio.audio')),
                ('download', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='playlist.playlistdownload')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('download', 'audio')},
            },
        ),
        migrations.AddIndex(
            model_name='playlistdownload',
            index=models.Index(fields=['user', 'status'], name='playlist_pl_user_id_43ca36_idx'),
        ),
        migrations.AddIndex(
            model_name='playlistdownload',
            index=models.Index(fields=['playlist', 'status'], name='playlist_pl_playlis_de1bfc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playlistdownload',
            unique_together={('playlist', 'user')},
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['owner', 'playlist_id'], name='playlist_pl_owner_i_06ab40_idx'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['owner', 'subscribed'], name='playlist_pl_owner_i_c5b24f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playlist',
            unique_together={('owner', 'playlist_id')},
        ),
    ]
