# Generated by Django 4.2.27 on 2026-02-03 12:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playlist', '0002_smart_playlists'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='smartplaylist',
            name='unique_smart_playlist_name_per_user',
        ),
        migrations.RenameIndex(
            model_name='smartplaylist',
            new_name='playlist_sm_owner_i_16773e_idx',
            old_name='playlist_sm_owner_i_7e7731_idx',
        ),
        migrations.RenameIndex(
            model_name='smartplaylist',
            new_name='playlist_sm_owner_i_422d99_idx',
            old_name='playlist_sm_owner_i_a9f5c4_idx',
        ),
        migrations.AlterUniqueTogether(
            name='smartplaylist',
            unique_together={('owner', 'name')},
        ),
    ]
