# Generated by Django 5.2.17 on 2026-10-01 17:24

from django.db import migrations


class Migration(migrations.Migration):
    """Drop the server-side playlist-download feature (never wired into the UI; its task
    imported a module that did not exist). The autodetector's RemoveField-first plan fails
    on SQLite, which rebuilds the table with a unique_together naming the removed field;
    dropping the child table, then the parent, removes the constraints with them."""

    dependencies = [
        ('playlist', '0003_remove_smartplaylist_unique_smart_playlist_name_per_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlaylistDownloadItem',
        ),
        migrations.DeleteModel(
            name='PlaylistDownload',
        ),
    ]
