# Generated by Django 4.2.27 on 2026-01-18 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('youtube_id', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('channel_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('completed', 'Completed'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('started_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('auto_start', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(help_text='User who owns this download', on_delete=django.db.models.deletion.CASCADE, related_name='download_queue', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-auto_start', 'added_date'],
            },
        ),
    ]
