# Generated by Django 5.2.17 on 2026-10-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadqueue',
            name='retry_count',
            field=models.PositiveIntegerField(default=0, help_text='Automatic re-queues since the last manual retry'),
        ),
    ]
