# Generated by Django 4.2.27 on 2026-01-18 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(db_index=True, max_length=50)),
                ('channel_name', models.CharField(max_length=200)),
                ('channel_description', models.TextField(blank=True)),
                ('channel_thumbnail', models.URLField(blank=True, max_length=500)),
                ('subscribed', models.BooleanField(default=True)),
                ('subscriber_count', models.IntegerField(default=0)),
                ('video_count', models.IntegerField(default=0)),
                ('last_refreshed', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True, help_text='Channel is active and available')),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('success', 'Success'), ('failed', 'Failed'), ('stale', 'Stale')], default='pending', help_text='Current sync status', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Last error message if sync failed')),
                ('downloaded_count', models.IntegerField(default=0, help_text='Downloaded videos count')),
                ('auto_download', models.BooleanField(default=True, help_text='Auto-download new videos from this channel')),
                ('download_quality', models.CharField(choices=[('auto', 'Auto'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('ultra', 'Ultra')], default='auto', max_length=20)),
                ('owner', models.ForeignKey(help_text='User who owns this channel subscription', on_delete=django.db.models.deletion.CASCADE, related_name='channels', to=settings.AUTH_USER_MODEL)),
                ('youtube_account', models.ForeignKey(blank=True, help_text='YouTube account used to subscribe to this channel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channels', to='user.useryoutubeaccount')),
            ],
            options={
                'ordering': ['channel_name'],
                'indexes': [models.Index(fields=['owner', 'channel_id'], name='channel_cha_owner_i_e027ef_idx'), models.Index(fields=['owner', 'subscribed'], name='channel_cha_owner_i_67db80_idx')],
                'unique_together': {('owner', 'channel_id')},
            },
        ),
    ]
