# Generated by Django 4.2 on 2026-05-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='auto_disabled',
            field=models.BooleanField(default=False, help_text='Auto-disabled because repeated invalid channel errors were detected'),
        ),
        migrations.AddField(
            model_name='channel',
            name='auto_disabled_reason',
            field=models.TextField(blank=True, help_text='Reason why this subscription was auto-disabled'),
        ),
        migrations.AddField(
            model_name='channel',
            name='consecutive_sync_failures',
            field=models.PositiveIntegerField(default=0, help_text='Consecutive sync failures for this subscription'),
        ),
        migrations.AddField(
            model_name='channel',
            name='last_failed_sync',
            field=models.DateTimeField(blank=True, help_text='Last time a sync attempt failed', null=True),
        ),
    ]
