# Generated by Django 4.2.30 on 2026-08-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_channel_failure_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='sync_depth',
            field=models.IntegerField(default=50, help_text='Number of most-recent videos to scan per sync (0 = entire channel history)'),
        ),
    ]
