# Generated by Django 4.2.27 on 2026-01-20 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('channel_name', models.CharField(max_length=200)),
                ('genre', models.CharField(blank=True, default='', max_length=100)),
                ('listened_at', models.DateTimeField(auto_now_add=True)),
                ('duration_listened', models.IntegerField(default=0, help_text='Duration listened in seconds')),
                ('completed', models.BooleanField(default=False, help_text='Whether the track was fully played')),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_events', to='audio.audio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Listening history',
                'ordering': ['-listened_at'],
                'indexes': [models.Index(fields=['user', '-listened_at'], name='stats_liste_user_id_6a7db3_idx'), models.Index(fields=['user', 'artist'], name='stats_liste_user_id_d6e24f_idx'), models.Index(fields=['user', 'channel_name'], name='stats_liste_user_id_65c420_idx'), models.Index(fields=['user', 'genre'], name='stats_liste_user_id_743bd3_idx')],
            },
        ),
    ]
