# Generated by Django 4.2.27 on 2026-02-03 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tracks_played', models.IntegerField(default=0)),
                ('duration_listened', models.IntegerField(default=0, help_text='Total seconds listened that day')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_streaks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='stats_liste_user_id_94f104_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('tracks_10', '🎵 First Steps'), ('tracks_50', '🎵 Music Explorer'), ('tracks_100', '🎵 Dedicated Listener'), ('tracks_500', '🎵 Music Enthusiast'), ('tracks_1000', '🎵 Audiophile'), ('tracks_5000', '🎵 Music Legend'), ('tracks_10000', '🎵 Sound Master'), ('hours_1', '⏱️ First Hour'), ('hours_10', '⏱️ Getting Started'), ('hours_24', '⏱️ Full Day'), ('hours_100', '⏱️ Dedicated Fan'), ('hours_500', '⏱️ Time Traveler'), ('hours_1000', '⏱️ Marathon Listener'), ('streak_3', '🔥 3-Day Streak'), ('streak_7', '🔥 Week Warrior'), ('streak_14', '🔥 Two Week Champion'), ('streak_30', '🔥 Monthly Master'), ('streak_60', '🔥 Two Month Hero'), ('streak_90', '🔥 Quarter King'), ('streak_180', '🔥 Half Year Legend'), ('streak_365', '🔥 Year-Long Dedication'), ('artists_10', '🎤 Artist Explorer'), ('artists_50', '🎤 Genre Hopper'), ('artists_100', '🎤 Music Wanderer'), ('artists_500', '🎤 Eclectic Taste'), ('channels_5', '📺 Channel Surfer'), ('channels_25', '📺 Content Explorer'), ('channels_50', '📺 Curator'), ('channels_100', '📺 Library Builder'), ('night_owl', '🦉 Night Owl'), ('early_bird', '🐦 Early Bird'), ('weekend_warrior', '🎉 Weekend Warrior'), ('genre_master', '🏆 Genre Master'), ('completionist', '✅ Completionist'), ('collector', '💿 Collector'), ('superfan', '⭐ Superfan')], max_length=50)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('context', models.JSONField(blank=True, default=dict, help_text='Additional context like the artist name for superfan')),
                ('seen', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'indexes': [models.Index(fields=['user', '-unlocked_at'], name='stats_achie_user_id_2fb418_idx'), models.Index(fields=['user', 'seen'], name='stats_achie_user_id_b019d9_idx')],
                'unique_together': {('user', 'achievement_type')},
            },
        ),
    ]
